# Generated by Django 4.1.1 on 2022-09-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researchdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('list_of_vaccines', models.TextField(blank=True, null=True)),
                ('last_close_contact', models.TextField(blank=True, null=True)),
                ('last_infected_date', models.TextField(blank=True, null=True)),
                ('total_infection', models.BigIntegerField(blank=True, null=True)),
                ('total_close_contact_as_infected', models.BigIntegerField(blank=True, null=True)),
                ('total_close_contact_with_infected', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'researchdata',
            },
        ),
        migrations.CreateModel(
            name='Researchers',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'researchers',
            },
        ),
    ]
